# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Code blog
tagline:          'A record of my stupidity'
description:      'A blog to keep track of my mistakes.'
url:              http://sgrieve.github.com
baseurl:          /

author:
  name:           'Stuart Grieve'
  url:            http://www.geos.ed.ac.uk/homes/s0675405/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sgrieve/sgrieve.github.io
