# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'why does that happen?'
tagline:          'A record of what I learn'
description:      'Keeping track of things I should remember. C++, Python, version control, GIS, et al.'
url:              http://sgrieve.github.com/sgrieve.github.io/
baseurl:          http://sgrieve.github.io/

author:
  name:           'Stuart Grieve'
  url:            http://www.geos.ed.ac.uk/homes/s0675405/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sgrieve/sgrieve.github.io
